"""Tests for the assessment export endpoint and build_assessment_markdown utility."""

from __future__ import annotations

from datetime import datetime
from unittest.mock import AsyncMock, MagicMock

import pytest
import pytest_asyncio
from fastapi import FastAPI
from httpx import ASGITransport, AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.db import AssessmentResult, AssessmentSession, Base, get_db
from app.routes.assessment import router
from app.routes.export_utils import build_assessment_markdown

# ── In-memory SQLite test database ──────────────────────────────────────────

_test_engine = create_async_engine("sqlite+aiosqlite:///:memory:")
_TestSessionFactory = async_sessionmaker(_test_engine, expire_on_commit=False)

# ── Minimal FastAPI app with the router ─────────────────────────────────────

_test_app = FastAPI()
_test_app.include_router(router, prefix="/api")


async def _override_get_db():
    async with _TestSessionFactory() as session:
        yield session


_test_app.dependency_overrides[get_db] = _override_get_db

_mock_graph = AsyncMock()
_test_app.state.graph = _mock_graph


# ── Fixtures ────────────────────────────────────────────────────────────────

FULL_KNOWLEDGE_GRAPH = {
    "nodes": [
        {
            "concept": "React Hooks",
            "confidence": 0.85,
            "bloom_level": "apply",
            "prerequisites": [],
            "evidence": ["Demonstrated useState usage", "Explained useEffect"],
        },
        {
            "concept": "TypeScript Generics",
            "confidence": 0.7,
            "bloom_level": "apply",
            "prerequisites": ["React Hooks"],
            "evidence": [],
        },
    ]
}

FULL_GAP_NODES = [
    {
        "concept": "Next.js App Router",
        "confidence": 0.6,
        "bloom_level": "apply",
        "prerequisites": ["React Hooks"],
    }
]

FULL_LEARNING_PLAN = {
    "summary": "Focus on deepening Next.js knowledge.",
    "total_hours": 20,
    "phases": [
        {
            "phase_number": 1,
            "title": "Next.js Deep Dive",
            "estimated_hours": 16,
            "rationale": "Biggest gap relative to target level",
            "concepts": ["App Router", "Server Actions"],
            "resources": [
                {
                    "title": "Next.js Docs",
                    "url": "https://nextjs.org/docs",
                    "type": "documentation",
                },
                {"title": "Internal Guide", "url": None, "type": "guide"},
            ],
        }
    ],
}

FULL_PROFICIENCY_SCORES = [
    {
        "skill_id": "react",
        "skill_name": "React",
        "score": 72,
        "confidence": 0.85,
        "bloom_level": "apply",
    }
]


@pytest_asyncio.fixture
async def setup_db():
    """Create tables before each test, drop after."""
    async with _test_engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    yield
    async with _test_engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)


# ── TestBuildAssessmentMarkdown ──────────────────────────────────────────────


class TestBuildAssessmentMarkdown:
    def test_full_data_contains_all_sections(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=datetime(2026, 3, 16),
            knowledge_graph=FULL_KNOWLEDGE_GRAPH,
            gap_nodes=FULL_GAP_NODES,
            learning_plan=FULL_LEARNING_PLAN,
            proficiency_scores=FULL_PROFICIENCY_SCORES,
        )
        assert "# Assessment Report" in md
        assert "## Proficiency Scores" in md
        assert "## Knowledge Map" in md
        assert "## Knowledge Gaps" in md
        assert "## Learning Plan" in md
        assert "*Generated by OpenLearning*" in md

    def test_all_none_renders_all_fallbacks(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=None,
        )
        assert "*No gaps identified.*" in md
        assert "*Learning plan not yet generated.*" in md
        assert "*Assessment not yet complete — knowledge map unavailable.*" in md

    def test_empty_phases_list(self):
        plan = {"summary": "A plan", "total_hours": 0, "phases": []}
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=plan,
            proficiency_scores=None,
        )
        assert "## Learning Plan" in md
        assert "> A plan" in md

    def test_resource_with_url_renders_link(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=FULL_LEARNING_PLAN,
            proficiency_scores=None,
        )
        assert "[Next.js Docs](https://nextjs.org/docs)" in md

    def test_resource_without_url_renders_plain(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=FULL_LEARNING_PLAN,
            proficiency_scores=None,
        )
        assert "Internal Guide — guide" in md

    def test_proficiency_score_table_renders(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=FULL_PROFICIENCY_SCORES,
        )
        assert "| React |" in md
        assert "72%" in md
        assert "85%" in md

    def test_snake_case_keys_used(self):
        """Confirm formatter reads skill_id/skill_name, not skillId/skillName."""
        camel_scores = [{"skillId": "react", "skillName": "React", "score": 72}]
        md_camel = build_assessment_markdown(
            session_id="s1",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=camel_scores,
        )
        # camelCase keys should NOT match — falls back to '—'
        assert "| — |" in md_camel

        snake_scores = [{"skill_id": "react", "skill_name": "React", "score": 72}]
        md_snake = build_assessment_markdown(
            session_id="s1",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=snake_scores,
        )
        assert "| React |" in md_snake

    def test_completed_at_formats_date(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="senior",
            completed_at=datetime(2026, 3, 16),
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=None,
        )
        assert "**Date:** 2026-03-16" in md

    def test_completed_at_none_renders_na(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=None,
        )
        assert "**Date:** N/A" in md


# ── TestAssessmentExportRoute ────────────────────────────────────────────────


class TestAssessmentExportRoute:
    async def _seed_session(self, db: AsyncSession, session_id: str = "sess-001") -> str:
        session = AssessmentSession(
            session_id=session_id,
            thread_id="thread-001",
            skill_ids=["react"],
            target_level="mid",
            status="completed",
        )
        db.add(session)
        await db.commit()
        return session_id

    async def _seed_result(self, db: AsyncSession, session_id: str = "sess-001") -> None:
        result = AssessmentResult(
            session_id=session_id,
            knowledge_graph=FULL_KNOWLEDGE_GRAPH,
            gap_nodes=FULL_GAP_NODES,
            learning_plan=FULL_LEARNING_PLAN,
            proficiency_scores=FULL_PROFICIENCY_SCORES,
        )
        db.add(result)
        await db.commit()

    @pytest.mark.asyncio
    async def test_export_session_not_found_returns_404(self, setup_db):
        async with AsyncClient(
            transport=ASGITransport(app=_test_app), base_url="http://test"
        ) as client:
            response = await client.get("/api/assessment/nonexistent/export")
        assert response.status_code == 404

    @pytest.mark.asyncio
    async def test_export_from_db_result_returns_200_markdown(self, setup_db):
        async with _TestSessionFactory() as db:
            await self._seed_session(db)
            await self._seed_result(db)

        async with AsyncClient(
            transport=ASGITransport(app=_test_app), base_url="http://test"
        ) as client:
            response = await client.get("/api/assessment/sess-001/export")

        assert response.status_code == 200
        assert "# Assessment Report" in response.text

    @pytest.mark.asyncio
    async def test_export_response_content_type_is_text_markdown(self, setup_db):
        async with _TestSessionFactory() as db:
            await self._seed_session(db)
            await self._seed_result(db)

        async with AsyncClient(
            transport=ASGITransport(app=_test_app), base_url="http://test"
        ) as client:
            response = await client.get("/api/assessment/sess-001/export")

        assert "text/markdown" in response.headers["content-type"]

    @pytest.mark.asyncio
    async def test_export_response_has_content_disposition_attachment(self, setup_db):
        async with _TestSessionFactory() as db:
            await self._seed_session(db)
            await self._seed_result(db)

        async with AsyncClient(
            transport=ASGITransport(app=_test_app), base_url="http://test"
        ) as client:
            response = await client.get("/api/assessment/sess-001/export")

        assert "attachment" in response.headers["content-disposition"]
        assert "sess-001"[:8] in response.headers["content-disposition"]

    @pytest.mark.asyncio
    async def test_export_response_has_content_length(self, setup_db):
        async with _TestSessionFactory() as db:
            await self._seed_session(db)
            await self._seed_result(db)

        async with AsyncClient(
            transport=ASGITransport(app=_test_app), base_url="http://test"
        ) as client:
            response = await client.get("/api/assessment/sess-001/export")

        assert "content-length" in response.headers
        assert int(response.headers["content-length"]) == len(response.content)

    @pytest.mark.asyncio
    async def test_export_falls_back_to_graph_state_when_no_db_row(self, setup_db):
        async with _TestSessionFactory() as db:
            await self._seed_session(db)
            # No AssessmentResult row — must fall back to graph state

        fake_kg = MagicMock()
        fake_kg.model_dump.return_value = FULL_KNOWLEDGE_GRAPH
        fake_kg.nodes = []

        fake_state_values = {
            "knowledge_graph": fake_kg,
            "gap_nodes": [],
            "learning_plan": None,
        }
        mock_graph_state = MagicMock()
        mock_graph_state.values = fake_state_values
        _mock_graph.aget_state = AsyncMock(return_value=mock_graph_state)

        try:
            async with AsyncClient(
                transport=ASGITransport(app=_test_app), base_url="http://test"
            ) as client:
                response = await client.get("/api/assessment/sess-001/export")

            assert response.status_code == 200
            assert "# Assessment Report" in response.text
        finally:
            _mock_graph.reset_mock()

    @pytest.mark.asyncio
    async def test_export_incomplete_assessment_returns_200_with_fallbacks(self, setup_db):
        async with _TestSessionFactory() as db:
            await self._seed_session(db)
            result = AssessmentResult(
                session_id="sess-001",
                knowledge_graph=None,
                gap_nodes=None,
                learning_plan=None,
                proficiency_scores=None,
            )
            db.add(result)
            await db.commit()

        async with AsyncClient(
            transport=ASGITransport(app=_test_app), base_url="http://test"
        ) as client:
            response = await client.get("/api/assessment/sess-001/export")

        assert response.status_code == 200
        assert "*No gaps identified.*" in response.text
        assert "*Learning plan not yet generated.*" in response.text
