"""Tests for the assessment export endpoint and build_assessment_markdown utility."""

from __future__ import annotations

from datetime import datetime
from unittest.mock import AsyncMock, MagicMock

import pytest
from httpx import ASGITransport, AsyncClient

from app.db import AssessmentResult
from app.routes.export_utils import build_assessment_markdown
from tests.conftest import (
    FULL_GAP_NODES,
    FULL_KNOWLEDGE_GRAPH,
    FULL_LEARNING_PLAN,
    FULL_PROFICIENCY_SCORES,
    _mock_graph,
    _test_app,
    _TestSessionFactory,
    seed_result,
    seed_session,
)

# ── TestBuildAssessmentMarkdown ──────────────────────────────────────────────


class TestBuildAssessmentMarkdown:
    def test_full_data_contains_all_sections(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=datetime(2026, 3, 16),
            knowledge_graph=FULL_KNOWLEDGE_GRAPH,
            gap_nodes=FULL_GAP_NODES,
            learning_plan=FULL_LEARNING_PLAN,
            proficiency_scores=FULL_PROFICIENCY_SCORES,
        )
        assert "# Assessment Report" in md
        assert "## Proficiency Scores" in md
        assert "## Knowledge Map" in md
        assert "## Knowledge Gaps" in md
        assert "## Learning Plan" in md
        assert "*Generated by OpenLearning*" in md

    def test_all_none_renders_all_fallbacks(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=None,
        )
        assert "*No gaps identified.*" in md
        assert "*Learning plan not yet generated.*" in md
        assert "*Assessment not yet complete — knowledge map unavailable.*" in md

    def test_empty_phases_list(self):
        plan = {"summary": "A plan", "total_hours": 0, "phases": []}
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=plan,
            proficiency_scores=None,
        )
        assert "## Learning Plan" in md
        assert "> A plan" in md

    def test_resource_with_url_renders_link(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=FULL_LEARNING_PLAN,
            proficiency_scores=None,
        )
        assert "[Next.js Docs](https://nextjs.org/docs)" in md

    def test_resource_with_javascript_url_renders_plain(self):
        plan = {
            "summary": "Test",
            "total_hours": 1,
            "phases": [
                {
                    "phase_number": 1,
                    "title": "Phase 1",
                    "estimated_hours": 1,
                    "rationale": "",
                    "concepts": [],
                    "resources": [
                        {
                            "title": "Evil Link",
                            "url": "javascript:alert(1)",
                            "type": "article",
                        }
                    ],
                }
            ],
        }
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=plan,
            proficiency_scores=None,
        )
        assert "javascript:" not in md
        assert "- Evil Link — article" in md

    def test_resource_without_url_renders_plain(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=FULL_LEARNING_PLAN,
            proficiency_scores=None,
        )
        assert "Internal Guide — guide" in md

    def test_proficiency_score_table_renders(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=FULL_PROFICIENCY_SCORES,
        )
        assert "| React |" in md
        assert "72%" in md
        assert "85%" in md

    def test_snake_case_keys_used(self):
        """Confirm formatter reads skill_id/skill_name, not skillId/skillName."""
        camel_scores = [{"skillId": "react", "skillName": "React", "score": 72}]
        md_camel = build_assessment_markdown(
            session_id="s1",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=camel_scores,
        )
        # camelCase keys should NOT match — falls back to '—'
        assert "| — |" in md_camel

        snake_scores = [{"skill_id": "react", "skill_name": "React", "score": 72}]
        md_snake = build_assessment_markdown(
            session_id="s1",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=snake_scores,
        )
        assert "| React |" in md_snake

    def test_completed_at_formats_date(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="senior",
            completed_at=datetime(2026, 3, 16),
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=None,
        )
        assert "**Date:** 2026-03-16" in md

    def test_completed_at_none_renders_na(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=None,
        )
        assert "**Date:** N/A" in md

    def test_materials_section_renders(self):
        materials = [
            {
                "concept_id": "distributed_systems",
                "quality_score": 0.9,
                "bloom_score": 0.85,
                "material": {
                    "sections": [
                        {
                            "type": "explanation",
                            "title": "Understanding CAP",
                            "body": "The CAP theorem states...",
                        },
                        {
                            "type": "code_example",
                            "title": "Async Example",
                            "body": "Here is an example:",
                            "code_block": "async def fetch(): ...",
                        },
                        {
                            "type": "quiz",
                            "title": "CAP Quiz",
                            "body": "What does CAP stand for?",
                            "answer": "Consistency, Availability, Partition tolerance",
                        },
                    ]
                },
            }
        ]
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=None,
            materials=materials,
        )
        assert "## Generated Learning Materials" in md
        assert "### Distributed Systems" in md
        assert "**Quality:** 90%" in md
        assert "#### Understanding CAP" in md
        assert "The CAP theorem states..." in md
        assert "~~~~\nasync def fetch(): ...\n~~~~" in md
        assert "#### CAP Quiz" in md
        assert "> **Answer:** Consistency, Availability, Partition tolerance" in md

    def test_materials_none_does_not_add_section(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=None,
            materials=None,
        )
        assert "Generated Learning Materials" not in md

    def test_materials_empty_list_does_not_add_section(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=None,
            materials=[],
        )
        assert "Generated Learning Materials" not in md

    def test_materials_malformed_sections_skipped(self):
        materials = [
            {
                "concept_id": "test_concept",
                "quality_score": 0.5,
                "bloom_score": 0.6,
                "material": {
                    "sections": "not-a-list",
                },
            },
            {
                "concept_id": "good_concept",
                "quality_score": 0.8,
                "bloom_score": 0.7,
                "material": {
                    "sections": [
                        {"type": "explanation", "title": "Good", "body": "Works"},
                    ]
                },
            },
        ]
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=None,
            materials=materials,
        )
        assert "### Good Concept" in md
        assert "#### Good" in md

    def test_materials_quality_flag_renders(self):
        materials = [
            {
                "concept_id": "test_concept",
                "quality_score": 0.5,
                "bloom_score": 0.6,
                "quality_flag": "review",
                "material": {"sections": []},
            }
        ]
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=None,
            materials=materials,
        )
        assert "**Flag:** review" in md

    def test_materials_code_block_with_backticks_uses_tilde_fence(self):
        """Tilde fencing prevents markdown injection from backticks in code."""
        materials = [
            {
                "concept_id": "injection_test",
                "quality_score": 0.8,
                "bloom_score": 0.7,
                "material": {
                    "sections": [
                        {
                            "type": "code_example",
                            "title": "Tricky Code",
                            "body": "Example:",
                            "code_block": "```\nmalicious\n```",
                        },
                    ]
                },
            }
        ]
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=None,
            materials=materials,
        )
        assert "~~~~\n```\nmalicious\n```\n~~~~" in md

    def test_materials_backward_compatible_with_existing_tests(self):
        """Existing call without materials arg still works."""
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=datetime(2026, 3, 16),
            knowledge_graph=FULL_KNOWLEDGE_GRAPH,
            gap_nodes=FULL_GAP_NODES,
            learning_plan=FULL_LEARNING_PLAN,
            proficiency_scores=FULL_PROFICIENCY_SCORES,
        )
        assert "# Assessment Report" in md
        assert "Generated Learning Materials" not in md


# ── TestAssessmentExportRoute ────────────────────────────────────────────────


class TestAssessmentExportRoute:
    @pytest.mark.asyncio
    async def test_export_session_not_found_returns_404(self, setup_db):
        async with AsyncClient(
            transport=ASGITransport(app=_test_app), base_url="http://test"
        ) as client:
            response = await client.get("/api/assessment/nonexistent/export")
        assert response.status_code == 404

    @pytest.mark.asyncio
    async def test_export_from_db_result_returns_200_markdown(self, setup_db):
        async with _TestSessionFactory() as db:
            await seed_session(db, status="completed")
            await seed_result(db)

        async with AsyncClient(
            transport=ASGITransport(app=_test_app), base_url="http://test"
        ) as client:
            response = await client.get("/api/assessment/sess-001/export")

        assert response.status_code == 200
        assert "# Assessment Report" in response.text

    @pytest.mark.asyncio
    async def test_export_response_content_type_is_text_markdown(self, setup_db):
        async with _TestSessionFactory() as db:
            await seed_session(db, status="completed")
            await seed_result(db)

        async with AsyncClient(
            transport=ASGITransport(app=_test_app), base_url="http://test"
        ) as client:
            response = await client.get("/api/assessment/sess-001/export")

        assert "text/markdown" in response.headers["content-type"]

    @pytest.mark.asyncio
    async def test_export_response_has_content_disposition_attachment(self, setup_db):
        async with _TestSessionFactory() as db:
            await seed_session(db, status="completed")
            await seed_result(db)

        async with AsyncClient(
            transport=ASGITransport(app=_test_app), base_url="http://test"
        ) as client:
            response = await client.get("/api/assessment/sess-001/export")

        assert "attachment" in response.headers["content-disposition"]
        assert "sess-001"[:8] in response.headers["content-disposition"]

    @pytest.mark.asyncio
    async def test_export_response_has_content_length(self, setup_db):
        async with _TestSessionFactory() as db:
            await seed_session(db, status="completed")
            await seed_result(db)

        async with AsyncClient(
            transport=ASGITransport(app=_test_app), base_url="http://test"
        ) as client:
            response = await client.get("/api/assessment/sess-001/export")

        assert "content-length" in response.headers
        assert int(response.headers["content-length"]) == len(response.content)

    @pytest.mark.asyncio
    async def test_export_falls_back_to_graph_state_when_no_db_row(self, setup_db):
        async with _TestSessionFactory() as db:
            await seed_session(db, status="completed")
            # No AssessmentResult row — must fall back to graph state

        fake_kg = MagicMock()
        fake_kg.model_dump.return_value = FULL_KNOWLEDGE_GRAPH
        fake_kg.nodes = []

        fake_state_values = {
            "knowledge_graph": fake_kg,
            "gap_nodes": [],
            "learning_plan": None,
        }
        mock_graph_state = MagicMock()
        mock_graph_state.values = fake_state_values
        _mock_graph.aget_state = AsyncMock(return_value=mock_graph_state)

        try:
            async with AsyncClient(
                transport=ASGITransport(app=_test_app), base_url="http://test"
            ) as client:
                response = await client.get("/api/assessment/sess-001/export")

            assert response.status_code == 200
            assert "# Assessment Report" in response.text
        finally:
            _mock_graph.reset_mock()

    @pytest.mark.asyncio
    async def test_export_incomplete_assessment_returns_200_with_fallbacks(self, setup_db):
        async with _TestSessionFactory() as db:
            await seed_session(db, status="completed")
            result = AssessmentResult(
                session_id="sess-001",
                knowledge_graph=None,
                gap_nodes=None,
                learning_plan=None,
                proficiency_scores=None,
            )
            db.add(result)
            await db.commit()

        async with AsyncClient(
            transport=ASGITransport(app=_test_app), base_url="http://test"
        ) as client:
            response = await client.get("/api/assessment/sess-001/export")

        assert response.status_code == 200
        assert "*No gaps identified.*" in response.text
        assert "*Learning plan not yet generated.*" in response.text
