"""Tests for the assessment export endpoint and build_assessment_markdown utility."""

from __future__ import annotations

from datetime import datetime
from unittest.mock import AsyncMock, MagicMock

import pytest
from httpx import ASGITransport, AsyncClient

from app.db import AssessmentResult
from app.routes.export_utils import _escape_md, _safe_url, build_assessment_markdown
from tests.conftest import (
    FULL_GAP_NODES,
    FULL_KNOWLEDGE_GRAPH,
    FULL_LEARNING_PLAN,
    FULL_PROFICIENCY_SCORES,
    LEGACY_LEARNING_PLAN_DICT,
    _mock_graph,
    _test_app,
    _TestSessionFactory,
    seed_result,
    seed_session,
)

# ── TestBuildAssessmentMarkdown ──────────────────────────────────────────────


class TestBuildAssessmentMarkdown:
    def test_full_data_contains_all_sections(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=datetime(2026, 3, 16),
            knowledge_graph=FULL_KNOWLEDGE_GRAPH,
            gap_nodes=FULL_GAP_NODES,
            learning_plan=FULL_LEARNING_PLAN,
            proficiency_scores=FULL_PROFICIENCY_SCORES,
        )
        assert "# Assessment Report" in md
        assert "## Proficiency Scores" in md
        assert "## Knowledge Map" in md
        assert "## Knowledge Gaps" in md
        assert "## Learning Plan" in md
        assert "*Generated by OpenLearning*" in md

    def test_all_none_renders_all_fallbacks(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=None,
        )
        assert "*No gaps identified.*" in md
        assert "*Learning plan not yet generated.*" in md
        assert "*Assessment not yet complete — knowledge map unavailable.*" in md

    def test_empty_phases_list(self):
        plan = {"summary": "A plan", "total_hours": 0, "phases": []}
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=plan,
            proficiency_scores=None,
        )
        assert "## Learning Plan" in md
        assert "> A plan" in md

    def test_resource_with_url_renders_link(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=FULL_LEARNING_PLAN,
            proficiency_scores=None,
        )
        assert "[Next.js Docs](https://nextjs.org/docs)" in md

    def test_resource_without_url_renders_plain(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=FULL_LEARNING_PLAN,
            proficiency_scores=None,
        )
        assert "Internal Guide — guide" in md

    def test_proficiency_score_table_renders(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=FULL_PROFICIENCY_SCORES,
        )
        assert "| React |" in md
        assert "72%" in md
        assert "85%" in md

    def test_snake_case_keys_used(self):
        """Confirm formatter reads skill_id/skill_name, not skillId/skillName."""
        camel_scores = [{"skillId": "react", "skillName": "React", "score": 72}]
        md_camel = build_assessment_markdown(
            session_id="s1",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=camel_scores,
        )
        # camelCase keys should NOT match — falls back to '—'
        assert "| — |" in md_camel

        snake_scores = [{"skill_id": "react", "skill_name": "React", "score": 72}]
        md_snake = build_assessment_markdown(
            session_id="s1",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=snake_scores,
        )
        assert "| React |" in md_snake

    def test_completed_at_formats_date(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="senior",
            completed_at=datetime(2026, 3, 16),
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=None,
        )
        assert "**Date:** 2026-03-16" in md

    def test_completed_at_none_renders_na(self):
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=None,
            proficiency_scores=None,
        )
        assert "**Date:** N/A" in md

    def test_build_assessment_markdown_new_plan_shape(self):
        """New nested concept shape renders one section per concept with its
        own resources."""
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=FULL_LEARNING_PLAN,
            proficiency_scores=None,
        )
        # Each concept is rendered as its own h4 section.
        assert "#### App Router" in md
        assert "#### Server Actions" in md
        # Descriptions render when non-empty.
        assert "Master server components" in md
        # Each concept's resources render under its own section.
        assert "[Next.js Docs](https://nextjs.org/docs)" in md
        assert "Internal Guide — guide" in md
        # The old phase-level "**Concepts:** ..." join line is gone.
        assert "**Concepts:** App Router, Server Actions" not in md

    def test_build_assessment_markdown_legacy_shape_still_renders(self):
        """Legacy JSONB rows (list[str] concepts + phase-level resources) must
        still render without crashing. Phase-level resources are dropped; each
        legacy concept becomes an empty section."""
        md = build_assessment_markdown(
            session_id="abc-123",
            target_level="mid",
            completed_at=None,
            knowledge_graph=None,
            gap_nodes=None,
            learning_plan=LEGACY_LEARNING_PLAN_DICT,
            proficiency_scores=None,
        )
        assert "## Learning Plan" in md
        assert "#### Legacy Concept A" in md
        assert "#### Legacy Concept B" in md
        # Dropped phase-level resource must not appear.
        assert "Old Resource" not in md


# ── Markdown escape helpers ────────────────────────────────────────────────


class TestEscapeMd:
    def test_none_and_empty_return_empty(self):
        assert _escape_md(None) == ""
        assert _escape_md("") == ""

    def test_escapes_link_metacharacters(self):
        assert _escape_md("[evil](javascript:alert(1))") == (
            "\\[evil\\]\\(javascript:alert\\(1\\)\\)"
        )

    def test_escapes_html_angle_brackets(self):
        assert _escape_md("<script>alert(1)</script>") == ("\\<script\\>alert\\(1\\)\\</script\\>")

    def test_escapes_pipe_for_table_injection(self):
        assert _escape_md("cell|break") == "cell\\|break"

    def test_collapses_newlines_to_spaces(self):
        assert _escape_md("line1\nline2\r\nline3") == "line1 line2 line3"

    def test_preserves_safe_punctuation(self):
        """Dots, hyphens, plusses are safe and should not be escaped."""
        assert _escape_md("Next.js App-Router v2+") == "Next.js App-Router v2+"


class TestSafeUrl:
    def test_none_and_empty(self):
        assert _safe_url(None) is None
        assert _safe_url("") is None

    def test_http_and_https_pass(self):
        assert _safe_url("https://example.com") == "https://example.com"
        assert _safe_url("http://example.com") == "http://example.com"

    def test_javascript_scheme_rejected(self):
        assert _safe_url("javascript:alert(1)") is None

    def test_data_scheme_rejected(self):
        assert _safe_url("data:text/html,<script>alert(1)</script>") is None

    def test_case_insensitive_scheme_check(self):
        assert _safe_url("HTTPS://EXAMPLE.COM") == "HTTPS://EXAMPLE.COM"
        assert _safe_url("JavaScript:alert(1)") is None

    def test_parentheses_url_encoded(self):
        url = "https://en.wikipedia.org/wiki/Foo_(bar)"
        result = _safe_url(url)
        assert result is not None
        assert ")" not in result
        assert "%29" in result


class TestMarkdownXssRegression:
    """End-to-end regression: LLM output with injection payloads must not
    produce exploitable markdown when rendered."""

    def test_xss_in_concept_name_escaped(self):
        plan = {
            "summary": "Safe",
            "total_hours": 1,
            "phases": [
                {
                    "phase_number": 1,
                    "title": "Phase",
                    "estimated_hours": 1,
                    "rationale": "",
                    "concepts": [
                        {
                            "key": "xss",
                            "name": "[Click me](javascript:alert(1))",
                            "description": "",
                            "resources": [],
                        }
                    ],
                }
            ],
        }
        md = build_assessment_markdown("s1", "mid", None, None, None, plan, None)
        # The brackets and parens must be escaped so the markdown renderer
        # does not create a clickable link.
        assert "\\[Click me\\]\\(javascript" in md
        # Unescaped link syntax must not appear.
        assert "[Click me](javascript:" not in md

    def test_xss_in_resource_url_dropped(self):
        plan = {
            "summary": "Safe",
            "total_hours": 1,
            "phases": [
                {
                    "phase_number": 1,
                    "title": "Phase",
                    "estimated_hours": 1,
                    "rationale": "",
                    "concepts": [
                        {
                            "key": "xss",
                            "name": "Normal",
                            "description": "",
                            "resources": [
                                {
                                    "type": "article",
                                    "title": "Evil Link",
                                    "url": "javascript:alert(document.cookie)",
                                }
                            ],
                        }
                    ],
                }
            ],
        }
        md = build_assessment_markdown("s1", "mid", None, None, None, plan, None)
        # The unsafe URL must be dropped — rendered as plain text, not a link.
        assert "javascript:" not in md
        assert "Evil Link" in md  # title still rendered as plain text

    def test_html_in_knowledge_graph_escaped(self):
        import re

        kg = {
            "nodes": [
                {
                    "concept": "<img src=x onerror=alert(1)>",
                    "confidence": 0.5,
                    "bloom_level": "apply",
                    "prerequisites": [],
                    "evidence": [],
                }
            ]
        }
        md = build_assessment_markdown("s1", "mid", None, kg, None, None, None)
        # The angle brackets must be escaped so the markdown renderer does
        # not treat them as raw HTML.
        assert "\\<img" in md
        assert "\\>" in md
        # No unescaped `<` before `img` — every `<` must be preceded by `\`.
        assert not re.search(r"(?<!\\)<img", md)


# ── TestAssessmentExportRoute ────────────────────────────────────────────────


class TestAssessmentExportRoute:
    @pytest.mark.asyncio
    async def test_export_session_not_found_returns_404(self, setup_db):
        async with AsyncClient(
            transport=ASGITransport(app=_test_app), base_url="http://test"
        ) as client:
            response = await client.get("/api/assessment/nonexistent/export")
        assert response.status_code == 404

    @pytest.mark.asyncio
    async def test_export_from_db_result_returns_200_markdown(self, setup_db):
        async with _TestSessionFactory() as db:
            await seed_session(db, status="completed")
            await seed_result(db)

        async with AsyncClient(
            transport=ASGITransport(app=_test_app), base_url="http://test"
        ) as client:
            response = await client.get("/api/assessment/sess-001/export")

        assert response.status_code == 200
        assert "# Assessment Report" in response.text

    @pytest.mark.asyncio
    async def test_export_response_content_type_is_text_markdown(self, setup_db):
        async with _TestSessionFactory() as db:
            await seed_session(db, status="completed")
            await seed_result(db)

        async with AsyncClient(
            transport=ASGITransport(app=_test_app), base_url="http://test"
        ) as client:
            response = await client.get("/api/assessment/sess-001/export")

        assert "text/markdown" in response.headers["content-type"]

    @pytest.mark.asyncio
    async def test_export_response_has_content_disposition_attachment(self, setup_db):
        async with _TestSessionFactory() as db:
            await seed_session(db, status="completed")
            await seed_result(db)

        async with AsyncClient(
            transport=ASGITransport(app=_test_app), base_url="http://test"
        ) as client:
            response = await client.get("/api/assessment/sess-001/export")

        assert "attachment" in response.headers["content-disposition"]
        assert "sess-001"[:8] in response.headers["content-disposition"]

    @pytest.mark.asyncio
    async def test_export_response_has_content_length(self, setup_db):
        async with _TestSessionFactory() as db:
            await seed_session(db, status="completed")
            await seed_result(db)

        async with AsyncClient(
            transport=ASGITransport(app=_test_app), base_url="http://test"
        ) as client:
            response = await client.get("/api/assessment/sess-001/export")

        assert "content-length" in response.headers
        assert int(response.headers["content-length"]) == len(response.content)

    @pytest.mark.asyncio
    async def test_export_falls_back_to_graph_state_when_no_db_row(self, setup_db):
        async with _TestSessionFactory() as db:
            await seed_session(db, status="completed")
            # No AssessmentResult row — must fall back to graph state

        fake_kg = MagicMock()
        fake_kg.model_dump.return_value = FULL_KNOWLEDGE_GRAPH
        fake_kg.nodes = []

        fake_state_values = {
            "knowledge_graph": fake_kg,
            "gap_nodes": [],
            "learning_plan": None,
        }
        mock_graph_state = MagicMock()
        mock_graph_state.values = fake_state_values
        _mock_graph.aget_state = AsyncMock(return_value=mock_graph_state)

        try:
            async with AsyncClient(
                transport=ASGITransport(app=_test_app), base_url="http://test"
            ) as client:
                response = await client.get("/api/assessment/sess-001/export")

            assert response.status_code == 200
            assert "# Assessment Report" in response.text
        finally:
            _mock_graph.reset_mock()

    @pytest.mark.asyncio
    async def test_export_incomplete_assessment_returns_200_with_fallbacks(self, setup_db):
        async with _TestSessionFactory() as db:
            await seed_session(db, status="completed")
            result = AssessmentResult(
                session_id="sess-001",
                knowledge_graph=None,
                gap_nodes=None,
                learning_plan=None,
                proficiency_scores=None,
            )
            db.add(result)
            await db.commit()

        async with AsyncClient(
            transport=ASGITransport(app=_test_app), base_url="http://test"
        ) as client:
            response = await client.get("/api/assessment/sess-001/export")

        assert response.status_code == 200
        assert "*No gaps identified.*" in response.text
        assert "*Learning plan not yet generated.*" in response.text
