import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { vi, beforeEach, afterEach } from "vitest";
import ExportPage from "./page";

// Must mock before any module that imports @/lib/api
vi.mock("@/lib/api", () => ({
  api: {
    assessmentExport: vi.fn(),
  },
}));

vi.mock("next/navigation", () => ({
  useParams: () => ({ id: "test-session-id-1234" }),
}));

import { api } from "@/lib/api";

const SAMPLE_MARKDOWN = `# Assessment Report

**Session:** \`test-session-id-1234\`
**Date:** 2026-03-16
**Target Level:** mid

---

*Generated by OpenLearning*`;

describe("ExportPage", () => {
  beforeEach(() => {
    vi.resetAllMocks();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("renders loading spinner initially", () => {
    // Hang the promise so the component stays in loading state
    (api.assessmentExport as ReturnType<typeof vi.fn>).mockReturnValue(new Promise(() => {}));
    const { container } = render(<ExportPage />);
    expect(container.querySelector(".animate-spin")).toBeTruthy();
  });

  it("renders markdown content after fetch resolves", async () => {
    (api.assessmentExport as ReturnType<typeof vi.fn>).mockResolvedValue(SAMPLE_MARKDOWN);
    render(<ExportPage />);
    await waitFor(() => {
      expect(screen.getByText(/# Assessment Report/)).toBeInTheDocument();
    });
  });

  it("renders error message when fetch rejects", async () => {
    (api.assessmentExport as ReturnType<typeof vi.fn>).mockRejectedValue(
      new Error("Session not found")
    );
    render(<ExportPage />);
    await waitFor(() => {
      expect(screen.getByText("Session not found")).toBeInTheDocument();
    });
  });

  it("renders generic error when rejection is not an Error instance", async () => {
    (api.assessmentExport as ReturnType<typeof vi.fn>).mockRejectedValue("oops");
    render(<ExportPage />);
    await waitFor(() => {
      expect(screen.getByText("Failed to load export")).toBeInTheDocument();
    });
  });

  it("Download button triggers Blob download", async () => {
    (api.assessmentExport as ReturnType<typeof vi.fn>).mockResolvedValue(SAMPLE_MARKDOWN);

    const mockObjectURL = "blob:http://localhost/mock";
    const createObjectURL = vi.fn().mockReturnValue(mockObjectURL);
    const revokeObjectURL = vi.fn();
    Object.defineProperty(window, "URL", {
      value: { createObjectURL, revokeObjectURL },
      writable: true,
    });

    const clickSpy = vi.fn();
    const createElementOrig = document.createElement.bind(document);
    vi.spyOn(document, "createElement").mockImplementation((tag: string) => {
      if (tag === "a") {
        const el = createElementOrig(tag) as HTMLAnchorElement;
        el.click = clickSpy;
        return el;
      }
      return createElementOrig(tag);
    });

    render(<ExportPage />);
    await waitFor(() => screen.getByText("Download .md"));

    await userEvent.click(screen.getByText("Download .md"));

    expect(createObjectURL).toHaveBeenCalledWith(expect.any(Blob));
    expect(clickSpy).toHaveBeenCalled();
    expect(revokeObjectURL).toHaveBeenCalledWith(mockObjectURL);
    // anchor must have been appended and removed from DOM
    expect(document.body.contains(document.querySelector("a[download]"))).toBe(false);
  });

  it("Print button calls window.print()", async () => {
    (api.assessmentExport as ReturnType<typeof vi.fn>).mockResolvedValue(SAMPLE_MARKDOWN);
    const printSpy = vi.fn();
    vi.spyOn(window, "print").mockImplementation(printSpy);

    render(<ExportPage />);
    await waitFor(() => screen.getByText("Print"));

    await userEvent.click(screen.getByText("Print"));

    expect(printSpy).toHaveBeenCalled();
  });
});
