export type {
  Skill,
  SkillsResponse,
  ProficiencyScore,
  GapItem,
  GapAnalysis,
  RoleSummary,
  RoleDetail,
  RoleLevelSummary,
  ConceptSummary,
  RoleConceptsResponse,
  AuthMeResponse,
  ApiKeyResponse,
  ValidateKeyResponse,
  RegisterRequest,
  LoginRequest,
  UserAssessmentSummary,
  AssessmentReportResponse,
  LearningPlanOut,
  LearningPhaseOut,
  ResourceOut,
} from "@/lib/generated/api-client";
