export type {
  Skill,
  SkillsResponse,
  ProficiencyScore,
  GapItem,
  GapAnalysis,
  LearningModule,
  LearningPlan,
  Phase,
  RoleSummary,
  RoleDetail,
  RoleLevelSummary,
  AuthMeResponse,
  ApiKeyResponse,
  ValidateKeyResponse,
  RegisterRequest,
  LoginRequest,
} from "@/lib/generated/api-client";
